# To learn more about the options available and their functionality, please
# visit the config.yml documentation on GitHub:
# https://github.com/cervinakuy/KitPvP/wiki/config.yml

Items:
  Kits:
    Enabled: true
    Name: '&e&lKit Selector &8(&7Right-Click&8)'
    Material: CHEST
    Slot: 0
    Menu: true
    Commands: []
  Leave:
    Enabled: true
    Name: '&e&lReturn to Hub &8(&7Right-Click&8)'
    Material: WATCH
    Slot: 1
    BungeeCord:
      Server: Hub-1
      Enabled: true
    Commands: []
Chat:
  Format: '%level% &e%player%: &f%message%'
  Enabled: false
Combat:
  HitSound:
    Sound: BLAZE_HIT
    Pitch: 1
    Enabled: true
  ArrowHit:
    Message: '%prefix% &e%player% &9is on &c%health%&9.'
    Enabled: true
  ArrowReturn:
    ItemName: '&eReturnable Arrow'
    NoSpace: '%prefix% &cYou must have at least one slot open in your inventory for
      you to receive your arrow for your successful shot.'
    Enabled: true
Kill:
  SoupReward:
    NoSpace: '%prefix% &c%amount% soups could not be added to your full inventory.'
    Amount: 1
    Delay: 0
    Enabled: true
  Commands: []
Death:
  Title:
    Title: '&c&lYOU DIED!'
    Subtitle: '&eYou will respawn in &c%seconds% &eseconds.'
    Time: 5
    Message: '%prefix% &6Respawning...'
  Sound:
    Sound: AMBIENCE_THUNDER
    Pitch: 1
    Enabled: false
  Commands: []
  Messages:
    Player: '%prefix%&a%victim% &9was killed by &a%killer% &c(%killer_health%).'
    Shot: '%prefix%&a%victim% &9was shot by &a%killer% &c(%killer_health%).'
    Fall: '%prefix%&a%victim% &9fell to their doom.'
    Void: '%prefix%&a%victim% &9died from the void.'
    Fire: '%prefix%&a%victim% &9died from fire.'
    Explosion: '%prefix%&a%victim% &9blew up.'
    Suicide: '%prefix%&a%victim% &9killed themselves.'
    Unknown: '%prefix%&a%victim% &9died.'
    Enabled: true
Respawn:
  Commands: []
PlayerTracker:
  Name: '&e&lPlayer Tracker'
  Message: '&e&lTarget: &c%nearestplayer% &e&lDistance: &d%distance%'
  NoneOnline: '&cNo Players Online'
  TrackBelowY: 128
  RefreshOnlyWhenHeld: true
Soups:
  Name: '&e&lSoups'
  RegenAmount: 6
  RemoveAfterUse: true
  Lore:
    - '&eUse this item to regain health.'
  Sound: EAT
  Pitch: 1
  Enabled: true
TNT:
  Name: '&aThrowable TNT &8(&7Right-Click&8)'
  Enabled: true
PreviewMenuBackArrowCommands:
  - 'player: kp menu'
Commands:
  Alias:
    Spawn: true
    Kit: true
    Kits: true
    Stats: true
Arena:
  ClearPotionEffectsOnJoin: true
  ClearInventoryOnJoin: true
  ClearInventoryOnLeave: false
  ClearInventoryOnRespawn: true
  ClearInventoryOnKit: true
  ClearKitOnCommandSpawn: true
  PreventBlockBreaking: true
  PreventBlockPlacing: true
  PreventItemDropping: true
  PreventHunger: true
  PreventItemDurabilityDamage: false
  PreventChestOpen: true
  PreventFallDamage: true
  PreventDeathDrops: true
  PreventArenaSignUseWithKit: true
  KeepWeatherAtSunny: true
  GiveItemsOnClear: true
  GiveItemsOnRespawn: true
  GiveItemsOnJoin: true
  NoKitProtection: true
  FancyDeath: false
  ResetKillStreakOnLeave: true
  ToSpawnOnJoin: true
  DeathParticles: true
Other:
  AutomaticallyAddKitToMenu: true
Spawn:
  Time: 5
  Enabled: true
Arenas:
  world:
    '1':
      World: world
      X: 0
      Y: 108
      Z: -1
      Yaw: -90.581604
      Pitch: -3.4502568