name: SoupPvP
authors:
 - Cervinakuy
 - Gami
 - atyre
main: com.planetgallium.kitpvp.Game
version: 2.2.1
description: The ultimate all-in-one SoupPvP plugin.
website: https://www.spigotmc.org/resources/27107/
softdepend: [PlaceholderAPI, WorldGuard]
api-version: 1.13

commands:
   souppvp:
     description: Main command.
     aliases: [Sp, Soup-PvP]
   ckit:
     description: Select a kit.
   cspawn:
     description: Teleports you to the spawn.
   ckits:
     description: View all available kits.
   cstats:
     description: View your stats.