Kit:
  Permission: kp.kit.Default
  Cooldown: 0
  Level: 0
  Health: 20
Inventory:
  Armor:
    Helmet:
      Material: IRON_HELMET
    Chestplate:
      Material: IRON_CHESTPLATE
      Enchantments:
        PROTECTION_ENVIRONMENTAL: 1
    Leggings:
      Material: IRON_LEGGINGS
    Boots:
      Material: IRON_BOOTS
  Items:
    '0':
      Material: DIAMOND_SWORD
      Enchantments:
        DAMAGE_ALL: 1
    'Fill':
      Name: '&e&lSoups'
      Lore:
      - '&eUse this item to regain health.'
      Material: MUSHROOM_SOUP
Effects:
  SPEED:
    Amplifier: 1
    Duration: 9938
Abilities:
  Example:
    Activator:
      Name: '&aDefault Ability &7(Must be modified in kit file)'
      Material: EMERALD
    Message:
      Message: '%prefix% &7You have used your ability.'
    Sound:
      Sound: NOTE_PLING
      Pitch: 1
      Volume: 1
    Effects:
      SPEED:
        Amplifier: 1
        Duration: 10
    Commands:
    - 'console: This command is run from the console, you can use %player%'
    - 'player: This command is run from the player, you can use %player%'
